---
title: Compilerfehler CS0156
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
f1_keywords: CS0156
helpviewer_keywords: CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: "9"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 1a24aa212e8f8c1c8e03cdbe583f4c3f5a2e7de1
ms.sourcegitcommit: bd1ef61f4bb794b25383d3d72e71041a5ced172e
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/18/2017
---
# <a name="compiler-error-cs0156"></a>Compilerfehler CS0156
In einer finally-Klausel, die in der nächsten einschließenden catch-Klausel geschachtelt ist, ist keine throw-Anweisung ohne Argumente zulässig.  
  
 Eine [throw](../../csharp/language-reference/keywords/throw.md) -Anweisung ohne Parameter kann nur in einer **catch** -Klausel vorkommen, die keine Parameter annimmt.  
  
 Weitere Informationen finden Sie unter [Ausnahmebehandlungsanweisungen](../../csharp/language-reference/keywords/exception-handling-statements.md) und [Ausnahmen und Ausnahmebehandlung](../../csharp/programming-guide/exceptions/index.md).  
  
 Im folgenden Beispiel wird CS0156 generiert:  
  
```  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
