<Type Name="FaultCallback" FullName="System.Activities.FaultCallback">
  <TypeSignature Language="C#" Value="public delegate void FaultCallback(NativeActivityFaultContext faultContext, Exception propagatedException, ActivityInstance propagatedFrom);" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed FaultCallback extends System.MulticastDelegate" />
  <TypeSignature Language="DocId" Value="T:System.Activities.FaultCallback" />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Delegate</BaseTypeName>
  </Base>
  <Parameters>
    <Parameter Name="faultContext" Type="System.Activities.NativeActivityFaultContext" />
    <Parameter Name="propagatedException" Type="System.Exception" />
    <Parameter Name="propagatedFrom" Type="System.Activities.ActivityInstance" />
  </Parameters>
  <ReturnValue>
    <ReturnType>System.Void</ReturnType>
  </ReturnValue>
  <Docs>
    <param name="faultContext">Der für das Überprüfen des Workflowfehlers angegebene <see cref="T:System.Activities.ActivityFaultContext" />.</param>
    <param name="propagatedException">Die Ausnahme, die den Fehler verursacht hat.</param>
    <param name="propagatedFrom">Die Aktivität, die die Ausnahme ausgelöst und den Fehler generiert hat.</param>
    <summary>Stellt die Methode dar, die aufgerufen wird, wenn eine geplante Aktivität oder eines ihrer untergeordneten Elemente den Status <see cref="F:System.Activities.ActivityInstanceState.Faulted" /> annimmt.</summary>
    <remarks>To be added.</remarks>
  </Docs>
</Type>
